version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:latest
    working_directory: ~/notes
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            make sphinx && make push

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job:
          filters:
            branches:
              only: master
